apiVersion: v1
kind: ConfigMap
metadata:
  name: imp-config
  namespace: redback
data:
  DEVICE_ID: "1"
  ATAK_TCP_1: 192.168.4.20:4242
  ATAK_TCP_2: 192.168.4.42:4242
  ODS_URL: "http://host.docker.internal:8086/detect"
  OCS1_URL: "http://ocs:80/classify"
  OCS2_URL: "http://ocs2:80/classify"
  ODS_THRESH: ".1"
  MAVLINK_SERIAL_ADDRESS: "/dev/serial0:921600"
  MAVLINK_USE_SERIAL: "true"
  MOAS_SERVICE_SLEEP: "20"
  MQTT_USER: "test"
  MQTT_PASSWD: "test"
  MQTT_ADDRESS: "192.168.4.135:1883"
  AQMP_URL: "amqp://test:test@192.168.4.135:5672/"
  CAMERA_PATH: "/dev/video0"
  CAMERA_FORMAT: "YUYV 4:2:2"
  CAMERA_WIDTH: "1280"
  CAMERA_HEIGHT: "720"
  APP_MODE: "PROD"
  MINIO_URL: "192.168.1.137:9000"
  MINIO_IMAGE_BUCKET: "drone-images"
  MINIO_ACCOUNT: "devstoreaccount1"
  MINIO_PASSWORD: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
  IMAGE_STORAGE_URL: "192.168.1.136:10000"
  IMAGE_STORAGE_ACCOUNT: "devstoreaccount1"
  IMAGE_STORAGE_ACCOUNT_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="

---

# Source: imp/templates/server/imp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imp-service
  namespace: redback
  labels:
    helm.sh/chart: imp-0.1.0
    app.kubernetes.io/name: imp-service
    app.kubernetes.io/instance: imp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: imp-service
      app.kubernetes.io/instance: imp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imp-service
        app.kubernetes.io/instance: imp
    spec:
      imagePullSecrets:
        - name: ase-ecr-credentials
      securityContext:
        {}
      containers:
        - name: imp
          image: "ecr.dbe-2q2szb3.microsoftdatabox.com:31001/imp:1.6.0-amd64"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2
              memory: 256Mi
            requests:
              cpu: 1m
              memory: 2Mi
          ports:
          - containerPort: 3000
          args:
          - basestationservice
          - --verbose
          envFrom:
            - configMapRef:
                name: imp-config
      volumes:
      - name: config-volume
        configMap:
          name: imp-config
