apiVersion: v1
kind: Namespace
metadata:
  name: nginx2
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

---
apiVersion: v1
kind: Namespace
metadata:
  name: drones2
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

---
apiVersion: v1
kind: Namespace
metadata:
  name: drones3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active